name: Planner Reminder

on:
  schedule:
    - cron: "0 7 * * *"   # täglich 07:00 UTC
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminder endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_BASE: ${{ secrets.RENDER_API_BASE }} # z.B. https://creator-ai-qqkr.onrender.com/api/v1
        run: |
          set -e
          if [ -z "$CRON_SECRET" ] || [ -z "$API_BASE" ]; then
            echo "Missing CRON_SECRET or RENDER_API_BASE secret"; exit 1
          fi
          curl -sS -X POST "$API_BASE/planner/remind" \
            -H "X-Cron-Secret: $CRON_SECRET" \
            -H "Content-Type: application/json"
